[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
libs = []
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 10_000

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
