// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import { Test } from "forge-std/Test.sol";
import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";

import { MordantCoalitionAdapter } from "../src/recourse/MordantCoalitionAdapter.sol";
import { ICviVerifier } from "../src/interfaces/ICviVerifier.sol";
import { MockERC20 } from "../src/mocks/MockERC20.sol";
import { MockEligibility } from "../src/mocks/MockEligibility.sol";
import { CoalitionSettlementFixture } from "./fixtures/CoalitionSettlementFixture.sol";

/// @dev The settlement path for a coalition release, driven by the digests a real 2-of-3 release
/// of the Go spine actually produced.
///
/// The fixture is regenerated by:
///   MORDANT_COALITION_FIXTURE_OUT=<abs path to test/fixtures/coalition-settlement.json> \
///     go test -run TestEmitCoalitionSettlementFixture ./governedfhe/
///
/// Using the real digests is the point. A test built on synthetic keccaks would prove the contract
/// is internally consistent; it would not show that what the spine releases is what this adapter
/// settles.
contract MordantCoalitionAdapterTest is Test {
    MordantCoalitionAdapter private adapter;
    MockERC20 private token;
    MockEligibility private eligibility;

    uint256 private constant ATTESTOR_KEY = 0xA11CE;
    uint256 private constant OTHER_KEY = 0xB0B;
    address private attestor;
    address private facility = address(0xFAC);
    address private owner = address(0x0E1);
    address private holderA = address(0xA1);
    address private holderB = address(0xB1);
    address private funder = address(0xF1);

    uint64 private constant CURE_WINDOW = 1 days;
    uint16 private constant REQUIRED_QUORUM = 2;
    uint256 private constant PAY_A = 600_000;
    uint256 private constant PAY_B = 400_000;
    uint256 private constant RESERVE = 5_000_000;

    /// @dev Read once from the fixture, so every pin below is the spine's own value.
    struct SpineRelease {
        bytes32 fheCaseId;
        bytes32 caseBindingDigest;
        bytes32 assetIdentityDigest;
        bytes32 coalitionResultDigest;
        bytes32 releaseTranscript;
        bytes32 participantArtifactDigestA;
        bytes32 participantArtifactDigestB;
        bytes32 coalitionAuthorityId;
        bytes32 releaseMode;
        bytes32 circuitDigest;
        bytes32 parameterFingerprint;
        uint16 servingQuorum;
        bool sameEconomicAsset;
        bool policyConflict;
    }

    SpineRelease private spine;

    function setUp() public {
        spine = _loadSpineRelease();
        attestor = vm.addr(ATTESTOR_KEY);
        token = new MockERC20("aUSDC", "aUSDC", 6);
        eligibility = new MockEligibility();
        eligibility.setEligible(facility, 3, true);
        eligibility.setEligible(holderA, 4, true);
        eligibility.setEligible(holderB, 4, true);
        adapter = _deploy();
        token.mint(funder, RESERVE * 4);
        vm.prank(funder);
        token.approve(address(adapter), type(uint256).max);
    }

    /// @dev The fixture is a generated Solidity library rather than a JSON file read at
    /// runtime. Foundry grants filesystem access only through foundry.toml, and that file is a
    /// frozen source: the reviewed build configuration of the contracts must not drift to make a
    /// test convenient. The values are still mechanical, emitted by the Go run that produced them.
    function _loadSpineRelease() private pure returns (SpineRelease memory loaded) {
        loaded.fheCaseId = CoalitionSettlementFixture.FHE_CASE_ID;
        loaded.caseBindingDigest = CoalitionSettlementFixture.CASE_BINDING_DIGEST;
        loaded.assetIdentityDigest = CoalitionSettlementFixture.ASSET_IDENTITY_DIGEST;
        loaded.coalitionResultDigest = CoalitionSettlementFixture.COALITION_RESULT_DIGEST;
        loaded.releaseTranscript = CoalitionSettlementFixture.RELEASE_TRANSCRIPT;
        loaded.participantArtifactDigestA = CoalitionSettlementFixture.PARTICIPANT_ARTIFACT_DIGEST_A;
        loaded.participantArtifactDigestB = CoalitionSettlementFixture.PARTICIPANT_ARTIFACT_DIGEST_B;
        loaded.coalitionAuthorityId = CoalitionSettlementFixture.COALITION_AUTHORITY_ID;
        loaded.releaseMode = CoalitionSettlementFixture.RELEASE_MODE;
        loaded.circuitDigest = CoalitionSettlementFixture.CIRCUIT_DIGEST;
        loaded.parameterFingerprint = CoalitionSettlementFixture.PARAMETER_FINGERPRINT;
        loaded.servingQuorum = CoalitionSettlementFixture.SERVING_QUORUM;
        loaded.sameEconomicAsset = CoalitionSettlementFixture.SAME_ECONOMIC_ASSET;
        loaded.policyConflict = CoalitionSettlementFixture.POLICY_CONFLICT;
    }

    function _deploy() private returns (MordantCoalitionAdapter) {
        return new MordantCoalitionAdapter(
            IERC20(address(token)),
            ICviVerifier(address(eligibility)),
            attestor,
            facility,
            owner,
            spine.assetIdentityDigest,
            spine.coalitionAuthorityId,
            REQUIRED_QUORUM,
            spine.releaseMode,
            spine.circuitDigest,
            spine.parameterFingerprint,
            CURE_WINDOW
        );
    }

    function _release(bytes32 runId)
        private
        view
        returns (MordantCoalitionAdapter.CoalitionRelease memory r)
    {
        r.runId = runId;
        r.fheCaseId = spine.fheCaseId;
        r.caseBindingDigest = spine.caseBindingDigest;
        r.assetIdentityDigest = spine.assetIdentityDigest;
        r.coalitionResultDigest = spine.coalitionResultDigest;
        r.releaseTranscript = spine.releaseTranscript;
        r.participantArtifactDigestA = spine.participantArtifactDigestA;
        r.participantArtifactDigestB = spine.participantArtifactDigestB;
        r.holderA = holderA;
        r.holderB = holderB;
        r.payoutA = PAY_A;
        r.payoutB = PAY_B;
        r.sameEconomicAsset = spine.sameEconomicAsset;
        r.policyConflict = spine.policyConflict;
        r.coalitionAuthorityId = spine.coalitionAuthorityId;
        r.servingQuorum = spine.servingQuorum;
        r.releaseMode = spine.releaseMode;
        r.circuitHash = spine.circuitDigest;
        r.parameterFingerprint = spine.parameterFingerprint;
        r.nonce = uint256(runId);
        r.issuedAt = uint64(block.timestamp);
        r.expiry = uint64(block.timestamp + 1 hours);
    }

    function _sign(MordantCoalitionAdapter.CoalitionRelease memory r, uint256 key)
        private
        view
        returns (bytes memory)
    {
        (uint8 v, bytes32 rr, bytes32 ss) = vm.sign(key, adapter.hashRelease(r));
        return abi.encodePacked(rr, ss, v);
    }

    function _fund(uint256 amount) private {
        vm.prank(funder);
        adapter.fundReserve(amount);
    }

    // -------------------------------------------------------------- the whole path

    /// @notice The end criterion: a real coalition release reaches an economic consequence, with
    /// no single release key anywhere in the path.
    function testRealCoalitionReleaseReachesPayout() public {
        assertTrue(spine.policyConflict, "the fixture must be the conflicting branch");
        assertEq(uint256(spine.servingQuorum), uint256(REQUIRED_QUORUM), "fixture quorum");

        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/real"));
        adapter.consumeCoalitionRelease(r, _sign(r, ATTESTOR_KEY));

        assertEq(adapter.caseState(r.runId), uint8(MordantCoalitionAdapter.CaseState.CureOpen));
        assertEq(adapter.openReserved(), PAY_A + PAY_B, "reserved on consume");
        assertTrue(adapter.solvent(), "solvent after consume");

        // Nobody cures, so the entitlement opens without anyone acting.
        vm.warp(block.timestamp + CURE_WINDOW + 1);
        adapter.finalize(r.runId);
        assertEq(adapter.caseState(r.runId), uint8(MordantCoalitionAdapter.CaseState.Entitled));

        adapter.claim(r.runId, true);
        adapter.claim(r.runId, false);

        assertEq(token.balanceOf(holderA), PAY_A, "holder A paid");
        assertEq(token.balanceOf(holderB), PAY_B, "holder B paid");
        assertEq(adapter.caseState(r.runId), uint8(MordantCoalitionAdapter.CaseState.Claimed));
        assertEq(adapter.entitledUnpaid(), 0, "no unpaid entitlement left");
        assertTrue(adapter.solvent(), "solvent after payout");
    }

    /// @notice The cure path returns the reserve rather than paying, and stays solvent.
    function testFacilityCureReturnsTheReserve() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/cured"));
        adapter.consumeCoalitionRelease(r, _sign(r, ATTESTOR_KEY));

        vm.prank(facility);
        adapter.cure(r.runId);

        assertEq(adapter.caseState(r.runId), uint8(MordantCoalitionAdapter.CaseState.Cured));
        assertEq(adapter.openReserved(), 0, "nothing left reserved");
        assertEq(adapter.availableReserve(), RESERVE, "reserve restored");
        assertTrue(adapter.solvent(), "solvent after cure");
    }

    // -------------------------------------------------------------- H-02 on chain

    /// @notice The circuit cannot produce a policy conflict without an asset match, so the adapter
    /// refuses that vector instead of settling it.
    function testNonCanonicalDecisionIsRefused() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/non-canonical"));
        r.sameEconomicAsset = false;
        r.policyConflict = true;
        bytes memory signature = _sign(r, ATTESTOR_KEY);
        vm.expectRevert(
            abi.encodeWithSelector(MordantCoalitionAdapter.NonCanonicalDecision.selector, false, true)
        );
        adapter.consumeCoalitionRelease(r, signature);
    }

    /// @notice The asset bit is an integrity constraint, never an economic input. An asset match
    /// with no policy conflict settles nothing, exactly as no match would.
    function testAssetMatchWithoutPolicyConflictPaysNothing() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/no-conflict"));
        r.sameEconomicAsset = true;
        r.policyConflict = false;
        r.payoutA = 0;
        r.payoutB = 0;
        adapter.consumeCoalitionRelease(r, _sign(r, ATTESTOR_KEY));

        assertEq(adapter.caseState(r.runId), uint8(MordantCoalitionAdapter.CaseState.Refused));
        assertEq(adapter.openReserved(), 0, "nothing reserved");
        assertEq(adapter.availableReserve(), RESERVE, "reserve untouched");
    }

    /// @notice A payout may not ride along on an absent policy conflict.
    function testPayoutOnNoPolicyConflictIsRefused() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/sneaky-payout"));
        r.policyConflict = false;
        bytes memory signature = _sign(r, ATTESTOR_KEY);
        vm.expectRevert(MordantCoalitionAdapter.PayoutOnNoConflict.selector);
        adapter.consumeCoalitionRelease(r, signature);
    }

    // -------------------------------------------------------------- identity and quorum

    /// @notice The release identity is the coalition's threshold manifest digest. Another
    /// coalition's identity does not settle here.
    function testForeignCoalitionAuthorityIsRefused() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/foreign"));
        bytes32 foreign = keccak256("another-threshold-manifest");
        r.coalitionAuthorityId = foreign;
        bytes memory signature = _sign(r, ATTESTOR_KEY);
        vm.expectRevert(
            abi.encodeWithSelector(
                MordantCoalitionAdapter.CoalitionAuthorityMismatch.selector, foreign, spine.coalitionAuthorityId
            )
        );
        adapter.consumeCoalitionRelease(r, signature);
    }

    /// @notice A release attesting a quorum of one is not the coalition this adapter settles.
    function testQuorumBelowTheManifestIsRefused() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/single"));
        r.servingQuorum = 1;
        bytes memory signature = _sign(r, ATTESTOR_KEY);
        vm.expectRevert(
            abi.encodeWithSelector(MordantCoalitionAdapter.QuorumTooSmall.selector, uint16(1), REQUIRED_QUORUM)
        );
        adapter.consumeCoalitionRelease(r, signature);
    }

    /// @notice A quorum of one cannot even be configured.
    function testDeployingWithAQuorumOfOneIsRefused() public {
        vm.expectRevert(
            abi.encodeWithSelector(MordantCoalitionAdapter.QuorumTooSmall.selector, uint16(1), uint16(2))
        );
        new MordantCoalitionAdapter(
            IERC20(address(token)),
            ICviVerifier(address(eligibility)),
            attestor,
            facility,
            owner,
            spine.assetIdentityDigest,
            spine.coalitionAuthorityId,
            1,
            spine.releaseMode,
            spine.circuitDigest,
            spine.parameterFingerprint,
            CURE_WINDOW
        );
    }

    // -------------------------------------------------------------- bridge and tampering

    /// @notice The bridge signature is a handoff, and only the pinned attestor's holds.
    function testAnotherSignerCannotAttest() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/other-signer"));
        bytes memory signature = _sign(r, OTHER_KEY);
        vm.expectRevert(
            abi.encodeWithSelector(MordantCoalitionAdapter.BadAttestor.selector, vm.addr(OTHER_KEY))
        );
        adapter.consumeCoalitionRelease(r, signature);
    }

    /// @notice Every field is inside the signature, so a substituted one invalidates it.
    function testTamperedFieldsInvalidateTheAttestation() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/tamper"));
        bytes memory signature = _sign(r, ATTESTOR_KEY);

        MordantCoalitionAdapter.CoalitionRelease memory movedPayout = r;
        movedPayout.payoutA = PAY_A + 1;
        vm.expectRevert();
        adapter.consumeCoalitionRelease(movedPayout, signature);

        MordantCoalitionAdapter.CoalitionRelease memory movedHolder = r;
        movedHolder.holderA = address(0xDEAD);
        vm.expectRevert();
        adapter.consumeCoalitionRelease(movedHolder, signature);

        MordantCoalitionAdapter.CoalitionRelease memory movedTranscript = r;
        movedTranscript.releaseTranscript = keccak256("another transcript");
        vm.expectRevert();
        adapter.consumeCoalitionRelease(movedTranscript, signature);
    }

    /// @notice One result settles once, even under a fresh run identifier.
    function testTheSameCoalitionResultCannotSettleTwice() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory first = _release(keccak256("run/one"));
        adapter.consumeCoalitionRelease(first, _sign(first, ATTESTOR_KEY));

        MordantCoalitionAdapter.CoalitionRelease memory second = _release(keccak256("run/two"));
        bytes memory signature = _sign(second, ATTESTOR_KEY);
        vm.expectRevert(
            abi.encodeWithSelector(
                MordantCoalitionAdapter.ResultConsumed.selector, spine.coalitionResultDigest
            )
        );
        adapter.consumeCoalitionRelease(second, signature);
    }

    /// @notice A release cannot reserve what the adapter does not hold.
    function testAReleaseBeyondTheReserveIsRefused() public {
        _fund(PAY_A);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/insolvent"));
        bytes memory signature = _sign(r, ATTESTOR_KEY);
        vm.expectRevert(
            abi.encodeWithSelector(
                MordantCoalitionAdapter.InsufficientReserve.selector, PAY_A + PAY_B, PAY_A
            )
        );
        adapter.consumeCoalitionRelease(r, signature);
    }

    /// @notice Reserved and entitled liabilities are never withdrawable by the owner.
    function testOwnerCannotWithdrawAReservedLiability() public {
        _fund(PAY_A + PAY_B);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/locked"));
        adapter.consumeCoalitionRelease(r, _sign(r, ATTESTOR_KEY));

        vm.prank(owner);
        vm.expectRevert(
            abi.encodeWithSelector(MordantCoalitionAdapter.InsufficientReserve.selector, uint256(1), uint256(0))
        );
        adapter.withdrawAvailable(owner, 1);
        assertTrue(adapter.solvent(), "solvent while the liability is open");
    }

    // ------------------------------------------- Cleanverse is load-bearing

    /// @notice An entitlement is not a permanent permission. The holder's identity is resolved
    /// live at the claim, so an eligibility that lapses between the release and the payout stops
    /// the payout.
    function testIdentityLapsingAfterTheReleaseStopsThePayout() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/identity-lapse"));
        adapter.consumeCoalitionRelease(r, _sign(r, ATTESTOR_KEY));
        vm.warp(block.timestamp + CURE_WINDOW + 1);
        adapter.finalize(r.runId);

        // The A-Pass behind holder A stops being valid after the result existed.
        eligibility.setEligible(holderA, 4, false);
        vm.expectRevert(abi.encodeWithSelector(MordantCoalitionAdapter.Ineligible.selector, holderA, uint8(4)));
        adapter.claim(r.runId, true);

        // The other holder, still eligible, is unaffected: the refusal is per identity.
        adapter.claim(r.runId, false);
        assertEq(token.balanceOf(holderB), PAY_B, "holder B paid");
        assertEq(token.balanceOf(holderA), 0, "holder A not paid");
        assertTrue(adapter.solvent(), "solvent with one entitlement unclaimed");
    }

    /// @notice The asset's own policy is a second, independent authority. A holder whose identity
    /// is still valid is still refused when the token's policy turns against the transfer.
    function testAssetPolicyTurningAgainstTheTransferStopsThePayout() public {
        _fund(RESERVE);
        MordantCoalitionAdapter.CoalitionRelease memory r = _release(keccak256("run/policy-turn"));
        adapter.consumeCoalitionRelease(r, _sign(r, ATTESTOR_KEY));
        vm.warp(block.timestamp + CURE_WINDOW + 1);
        adapter.finalize(r.runId);

        // Identity stays valid; only the asset policy refuses.
        eligibility.setAssetTransferAllowed(holderA, false);
        assertTrue(eligibility.isEligible(holderA, 4), "the identity gate still passes");
        vm.expectRevert(
            abi.encodeWithSelector(MordantCoalitionAdapter.TransferPolicyDenied.selector, holderA, PAY_A)
        );
        adapter.claim(r.runId, true);

        // And it is recoverable: the entitlement is not destroyed, only unclaimable while refused.
        eligibility.setAssetTransferAllowed(holderA, true);
        adapter.claim(r.runId, true);
        assertEq(token.balanceOf(holderA), PAY_A, "holder A paid once the policy allows again");
    }

    /// @notice The circuit and parameters the adapter pins are the ones the spine ran.
    function testTheSpinePinsMatchTheDeployedReviewedValues() public view {
        assertEq(
            spine.circuitDigest,
            bytes32(0x2c16603974671e3de32f9023f0e205bedeb0e0553e663d12c37e42822aaddf2e),
            "circuit digest drifted from the reviewed deployment"
        );
        assertEq(
            spine.parameterFingerprint,
            bytes32(0xd0f85e99048a71163f218e8a6e12e7c21ddd5188527ae637a3b9cd16ff7c25d6),
            "parameter fingerprint drifted from the reviewed deployment"
        );
        assertEq(
            spine.assetIdentityDigest,
            bytes32(0x7613136ebe7efb777c78cdf8bd73a5a3e5604b005875e05e1427cce9dbc4c95c),
            "asset identity drifted from the reviewed deployment"
        );
    }
}
