import type { Abi } from "viem";

/**
 * Read-only surface copied from the currently compiled MordantInvoiceVault ABI.
 * Deliberately excludes every state-changing function.
 */
export const mordantInvoiceVaultReadAbi = [
  {
    type: "function",
    name: "invoiceRoot",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "protectionState",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum MordantInvoiceVault.ProtectionState",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "receivableState",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum MordantInvoiceVault.ReceivableState",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sequence",
    inputs: [],
    outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialUnits",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cvaAccounted",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cvaBurned",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "faceValue",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialBond",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bondLocked",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bondReturned",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entitlementAllocated",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entitlementClaimed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entitlementClaimedUnits",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entitlementSnapshotSequence",
    inputs: [],
    outputs: [{ name: "", type: "uint48", internalType: "uint48" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entitlementSnapshotSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "redemptionEscrow",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "redeemedFace",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "defaultCvaReleaseStarted",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accountedSettlementBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "assertAccounting",
    inputs: [],
    outputs: [],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingConflict",
    inputs: [],
    outputs: [
      { name: "commitment", type: "bytes32", internalType: "bytes32" },
      { name: "facility", type: "address", internalType: "address" },
      { name: "snapshotSequence", type: "uint48", internalType: "uint48" },
      { name: "snapshotSupply", type: "uint208", internalType: "uint208" },
      { name: "snapshotBond", type: "uint256", internalType: "uint256" },
      { name: "committedAt", type: "uint64", internalType: "uint64" },
      { name: "revealDeadline", type: "uint64", internalType: "uint64" },
      { name: "cureDeadline", type: "uint64", internalType: "uint64" },
      {
        name: "conflictingPledgeDigest",
        type: "bytes32",
        internalType: "bytes32",
      },
      { name: "conflictSigner", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
] as const satisfies Abi;
