#!/usr/bin/env node

// Bounded V3 laboratory runner. It is intentionally isolated from V2 and
// deploys only the verifier plus non-economic LaboratoryRecourseConsumer.
import { readFile, mkdir, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { performance } from "node:perf_hooks";
import {
  createPublicClient, createWalletClient, defineChain, encodeAbiParameters,
  encodeDeployData, encodeFunctionData, getAddress, getContractAddress, http,
  isAddress, keccak256, parseEventLogs, stringToHex,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { V3_ATTESTATION_TYPES, V3_EIP712_NAME, V3_EIP712_VERSION } from "../shared/scripts/canonical-v3.mjs";
import { lastProcessRunRoot, runProcessSeparatedV3 } from "../privacy-v3/process-run.mjs";

const HERE = dirname(fileURLToPath(import.meta.url)), LAB = resolve(HERE, "..");
const CHAIN_ID = 10_143, POLICY_ID = "0xbd26a38240747b4fb4363d5edc5d5f8d6729d1024aa343bc6115ca20013a8540", POLICY_VERSION = 1;
const MAX_CREATION = 131_072, MAX_GAS = 30_000_000n, ZERO = "0x0000000000000000000000000000000000000000";
const ROLE = keccak256(stringToHex("mordant.role.facility.v1")), CONSEQUENCE = keccak256(stringToHex("mordant.consequence.review-required.v1"));
function fail(code) { const e = new Error(code); e.code = code; throw e; }
function required(v, code) { if (typeof v !== "string" || !v.trim()) fail(code); return v.trim(); }
function key(v, code) { const value = required(v, code); if (!/^0x[\da-fA-F]{64}$/.test(value)) fail(code); return value; }
function address(v, code) { const value = required(v, code); if (!isAddress(value) || value.toLowerCase() === ZERO) fail(code); return getAddress(value); }
function args(argv) { let mode = null, out = null; for (let i=0;i<argv.length;i+=1) { if (["--check","--run"].includes(argv[i]) && !mode) { mode=argv[i].slice(2); continue; } if (argv[i]==="--out" && !out && argv[i+1]) { out=resolve(process.cwd(),argv[++i]); continue; } fail("CLI_ARGUMENT"); } if (!mode || (mode==="run") !== Boolean(out)) fail("CLI_MODE"); return {mode,out}; }
function config(env=process.env) { const deployer = privateKeyToAccount(key(env.FHE_MONAD_DEPLOYER_PRIVATE_KEY,"CONFIG_DEPLOYER_KEY")); const expected=address(env.FHE_MONAD_DEPLOYER_ADDRESS,"CONFIG_DEPLOYER_ADDRESS"); if(deployer.address.toLowerCase()!==expected.toLowerCase())fail("DEPLOYER_ADDRESS_MISMATCH"); const validators=[1,2,3].map(i=>privateKeyToAccount(key(env[`FHE_MONAD_VALIDATOR_${i}_PRIVATE_KEY`],`CONFIG_VALIDATOR_${i}_KEY`))); const all=new Set(validators.map(v=>v.address.toLowerCase()));if(all.size!==3||all.has(deployer.address.toLowerCase()))fail("VALIDATOR_IDENTITIES_INVALID");return {rpc:required(env.FHE_MONAD_RPC_URL,"CONFIG_RPC_URL"),deployer,validators,vault:address(env.FHE_MONAD_TEST_VAULT,"CONFIG_TEST_VAULT")}; }
function chain(rpc){return defineChain({id:CHAIN_ID,name:"Monad testnet",nativeCurrency:{name:"Monad",symbol:"MON",decimals:18},rpcUrls:{default:{http:[rpc]}}});}
async function artifact(name){let raw;try{raw=await readFile(resolve(LAB,`monad-adapter/out/${name}.sol/${name}.json`),"utf8");}catch{fail("V3_ARTIFACT_MISSING");}const parsed=JSON.parse(raw);if(!parsed.abi||!/^0x[\da-fA-F]+$/.test(parsed.bytecode?.object??""))fail("V3_ARTIFACT_INVALID");return {abi:parsed.abi,bytecode:parsed.bytecode.object};}
function size(hex){return (hex.length-2)/2;}
async function preflight(c, artifacts){const client=createPublicClient({chain:chain(c.rpc),transport:http(c.rpc)});const [id,balance,nonce,gasPrice]=await Promise.all([client.getChainId(),client.getBalance({address:c.deployer.address}),client.getTransactionCount({address:c.deployer.address}),client.getGasPrice()]);if(id!==CHAIN_ID)fail("CHAIN_ID_MISMATCH");const verifierInit=encodeDeployData({abi:artifacts.verifier.abi,bytecode:artifacts.verifier.bytecode,args:[c.deployer.address,c.validators.map(v=>v.address),2n]});if(size(verifierInit)>MAX_CREATION||size(artifacts.consumer.bytecode)>MAX_CREATION)fail("MONAD_CODE_SIZE_LIMIT");if(balance===0n)fail("DEPLOYER_MON_INSUFFICIENT");return {client,chain:chain(c.rpc),network:{chainId:id,balance:balance.toString(),nonce:nonce.toString(),gasPrice:gasPrice.toString()},verifierInit};}
async function send(wallet, client, request,label){let gas;try{gas=await client.estimateGas({...request,account:wallet.account.address});}catch{fail(`${label}_GAS_UNAVAILABLE`);}if(gas===0n||gas>MAX_GAS)fail(`${label}_GAS_LIMIT`);const hash=await wallet.sendTransaction({...request,gas});const receipt=await client.waitForTransactionReceipt({hash});if(receipt.status!=="success")fail(`${label}_REVERTED`);return {hash,receipt,gasEstimate:gas};}
async function write(path, value){await mkdir(dirname(path),{recursive:true});const temp=`${path}.tmp`;await writeFile(temp,`${JSON.stringify(value,null,2)}\n`);await rename(temp,path);}

export async function run(options=args(process.argv.slice(2))){const c=config();const artifacts={verifier:await artifact("ECDSAQuorumConfidentialPolicyVerifierV3"),consumer:await artifact("LaboratoryRecourseConsumer")};const pre=await preflight(c,artifacts);const report={schemaVersion:"mordant.fhe-monad-v3-recourse/1",testAssetsOnly:true,classification:"MONAD V3 ATOMIC RECOURSE: NOT PROVEN",network:pre.network,transactions:{verifier:null,consumer:null,policy:null,openRecourse:null},readbacks:null,replay:null,performance:null};if(options.mode==="check")return report;
 const wallet=createWalletClient({account:c.deployer,chain:pre.chain,transport:http(c.rpc)});const started=performance.now();const verifierTx=await send(wallet,pre.client,{data:pre.verifierInit},"VERIFIER_DEPLOY");const verifier=getContractAddress({from:c.deployer.address,nonce:BigInt(pre.network.nonce)});const consumerInit=encodeDeployData({abi:artifacts.consumer.abi,bytecode:artifacts.consumer.bytecode,args:[verifier,c.vault,POLICY_ID,POLICY_VERSION,ROLE,3600n,CONSEQUENCE]});const consumerTx=await send(wallet,pre.client,{data:consumerInit},"CONSUMER_DEPLOY");const consumer=getContractAddress({from:c.deployer.address,nonce:BigInt(pre.network.nonce)+1n});const policyData=encodeFunctionData({abi:artifacts.verifier.abi,functionName:"setPolicyVersion",args:[c.vault,POLICY_ID,POLICY_VERSION]});const policyTx=await send(wallet,pre.client,{to:verifier,data:policyData},"POLICY_CONFIG");
 const processStarted=performance.now();let processRun;try{processRun=await runProcessSeparatedV3({root:null,chainId:String(CHAIN_ID),vault:c.vault,policyId:POLICY_ID,consumer,nonce:null,validUntil:null});}catch(error){report.processRunRoot=lastProcessRunRoot();report.transactions={verifier:{hash:verifierTx.hash},consumer:{hash:consumerTx.hash},policy:{hash:policyTx.hash},openRecourse:null};if(options.out)await write(options.out,report);throw error;}const result=processRun.result.result;if(!result.conflictConfirmed)fail("FHE_CONFLICT_NOT_CONFIRMED");const validatorSet=await pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"validatorSetId"});const domain={name:V3_EIP712_NAME,version:V3_EIP712_VERSION,chainId:CHAIN_ID,verifyingContract:verifier};const message={validatorSetId:validatorSet,resultDigest:await pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"resultDigest",args:[result]})};const signed=await Promise.all(c.validators.slice(0,2).map(async validator=>({address:validator.address.toLowerCase(),signature:await validator.signTypedData({domain,types:V3_ATTESTATION_TYPES,primaryType:"ConfidentialPolicyAttestation",message})})));signed.sort((a,b)=>a.address.localeCompare(b.address));const attestation=encodeAbiParameters([{type:"bytes32"},{type:"bytes[]"}],[validatorSet,signed.map(v=>v.signature)]);const openData=encodeFunctionData({abi:artifacts.consumer.abi,functionName:"openRecourse",args:[result,attestation]});const openStarted=performance.now();const openTx=await send(wallet,pre.client,{to:consumer,data:openData},"ATOMIC_RECOURSE");
 const [replayKey,decisionKey,proofUsed,nonceUsed,decisionUsed,record]=await Promise.all([pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"replayKey",args:[result]}),pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"decisionKey",args:[result]}),pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"consumedProviderProofCommitments",args:[result.providerProofCommitment]}),pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"consumedReplayKeys",args:[await pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"replayKey",args:[result]})]}),pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"consumedDecisionKeys",args:[await pre.client.readContract({address:verifier,abi:artifacts.verifier.abi,functionName:"decisionKey",args:[result]})]}),pre.client.readContract({address:consumer,abi:artifacts.consumer.abi,functionName:"recourses",args:[result.resultCommitment]})]);let replayRejected=false;try{await pre.client.call({to:consumer,data:openData,account:c.deployer.address});}catch{replayRejected=true;}if(!replayRejected)fail("REPLAY_NOT_REJECTED");const verifierEvents=parseEventLogs({abi:artifacts.verifier.abi,logs:openTx.receipt.logs,eventName:"ConfidentialPolicyResultV3Accepted",strict:true});const recourseEvents=parseEventLogs({abi:artifacts.consumer.abi,logs:openTx.receipt.logs,eventName:"LaboratoryRecourseOpened",strict:true});if(verifierEvents.length!==1||recourseEvents.length!==1)fail("ATOMIC_EVENT_MISSING");report.classification="MONAD V3 ATOMIC RECOURSE: PROVEN";report.transactions={verifier:{hash:verifierTx.hash},consumer:{hash:consumerTx.hash},policy:{hash:policyTx.hash},openRecourse:{hash:openTx.hash,block:openTx.receipt.blockNumber.toString(),blockHash:openTx.receipt.blockHash}};report.readbacks={verifier,consumer,resultCommitment:result.resultCommitment,providerProofConsumed:proofUsed,nonceConsumed:nonceUsed,decisionConsumed:decisionUsed,replayKey,decisionKey,recourseRecord:record,verifierEvent:true,recourseEvent:true};report.replay={mode:"eth_call",rejected:true,secondTransactionBroadcast:false};report.performance={fheMilliseconds:Number((openStarted-processStarted).toFixed(2)),resultToReceiptMilliseconds:Number((performance.now()-openStarted).toFixed(2)),calldataBytes:size(openData),gasUsed:openTx.receipt.gasUsed.toString(),totalMilliseconds:Number((performance.now()-started).toFixed(2))};await write(options.out,report);return report;}
async function main(){try{process.stdout.write(`${JSON.stringify(await run(),null,2)}\n`);}catch(error){process.stdout.write(`${JSON.stringify({ok:false,classification:"MONAD V3 ATOMIC RECOURSE: NOT PROVEN",failedGate:error.code??"V3_RUNNER_FAILED"})}\n`);process.exitCode=1;}}
if(resolve(process.argv[1]??"")===fileURLToPath(import.meta.url))await main();
